// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oktagon_odoo_golang_amqp/protoModel/productTemplate.proto

package protoModel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductBundleDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ListPrice            float64  `protobuf:"fixed64,4,opt,name=listPrice,proto3" json:"listPrice,omitempty"`
	Cost                 float64  `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductBundleDetail) Reset()         { *m = ProductBundleDetail{} }
func (m *ProductBundleDetail) String() string { return proto.CompactTextString(m) }
func (*ProductBundleDetail) ProtoMessage()    {}
func (*ProductBundleDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad1a6a864f447bb7, []int{0}
}

func (m *ProductBundleDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductBundleDetail.Unmarshal(m, b)
}
func (m *ProductBundleDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductBundleDetail.Marshal(b, m, deterministic)
}
func (m *ProductBundleDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductBundleDetail.Merge(m, src)
}
func (m *ProductBundleDetail) XXX_Size() int {
	return xxx_messageInfo_ProductBundleDetail.Size(m)
}
func (m *ProductBundleDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductBundleDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProductBundleDetail proto.InternalMessageInfo

func (m *ProductBundleDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductBundleDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductBundleDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductBundleDetail) GetListPrice() float64 {
	if m != nil {
		return m.ListPrice
	}
	return 0
}

func (m *ProductBundleDetail) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type Product struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ListPrice            float64                `protobuf:"fixed64,4,opt,name=listPrice,proto3" json:"listPrice,omitempty"`
	Cost                 float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Volume               float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Weight               float64                `protobuf:"fixed64,7,opt,name=weight,proto3" json:"weight,omitempty"`
	CategoryId           int64                  `protobuf:"varint,8,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Category             string                 `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	CategoryCode         string                 `protobuf:"bytes,10,opt,name=categoryCode,proto3" json:"categoryCode,omitempty"`
	UomSalesId           int64                  `protobuf:"varint,11,opt,name=uomSalesId,proto3" json:"uomSalesId,omitempty"`
	UomSales             string                 `protobuf:"bytes,12,opt,name=uomSales,proto3" json:"uomSales,omitempty"`
	UomPurchaseId        int64                  `protobuf:"varint,13,opt,name=uomPurchaseId,proto3" json:"uomPurchaseId,omitempty"`
	UomPurchase          string                 `protobuf:"bytes,14,opt,name=uomPurchase,proto3" json:"uomPurchase,omitempty"`
	Sku                  string                 `protobuf:"bytes,15,opt,name=sku,proto3" json:"sku,omitempty"`
	BrandId              int64                  `protobuf:"varint,16,opt,name=brandId,proto3" json:"brandId,omitempty"`
	Brand                string                 `protobuf:"bytes,17,opt,name=brand,proto3" json:"brand,omitempty"`
	IsBundle             bool                   `protobuf:"varint,18,opt,name=isBundle,proto3" json:"isBundle,omitempty"`
	CreateDate           int64                  `protobuf:"varint,19,opt,name=createDate,proto3" json:"createDate,omitempty"`
	ProductBundleDetail  []*ProductBundleDetail `protobuf:"bytes,20,rep,name=productBundleDetail,proto3" json:"productBundleDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad1a6a864f447bb7, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetListPrice() float64 {
	if m != nil {
		return m.ListPrice
	}
	return 0
}

func (m *Product) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Product) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Product) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetCategoryCode() string {
	if m != nil {
		return m.CategoryCode
	}
	return ""
}

func (m *Product) GetUomSalesId() int64 {
	if m != nil {
		return m.UomSalesId
	}
	return 0
}

func (m *Product) GetUomSales() string {
	if m != nil {
		return m.UomSales
	}
	return ""
}

func (m *Product) GetUomPurchaseId() int64 {
	if m != nil {
		return m.UomPurchaseId
	}
	return 0
}

func (m *Product) GetUomPurchase() string {
	if m != nil {
		return m.UomPurchase
	}
	return ""
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetBrandId() int64 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *Product) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Product) GetIsBundle() bool {
	if m != nil {
		return m.IsBundle
	}
	return false
}

func (m *Product) GetCreateDate() int64 {
	if m != nil {
		return m.CreateDate
	}
	return 0
}

func (m *Product) GetProductBundleDetail() []*ProductBundleDetail {
	if m != nil {
		return m.ProductBundleDetail
	}
	return nil
}

type AllProduct struct {
	Product              []*Product `protobuf:"bytes,1,rep,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AllProduct) Reset()         { *m = AllProduct{} }
func (m *AllProduct) String() string { return proto.CompactTextString(m) }
func (*AllProduct) ProtoMessage()    {}
func (*AllProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad1a6a864f447bb7, []int{2}
}

func (m *AllProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllProduct.Unmarshal(m, b)
}
func (m *AllProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllProduct.Marshal(b, m, deterministic)
}
func (m *AllProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllProduct.Merge(m, src)
}
func (m *AllProduct) XXX_Size() int {
	return xxx_messageInfo_AllProduct.Size(m)
}
func (m *AllProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_AllProduct.DiscardUnknown(m)
}

var xxx_messageInfo_AllProduct proto.InternalMessageInfo

func (m *AllProduct) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductBundleDetail)(nil), "protoModel.ProductBundleDetail")
	proto.RegisterType((*Product)(nil), "protoModel.Product")
	proto.RegisterType((*AllProduct)(nil), "protoModel.AllProduct")
}

func init() {
	proto.RegisterFile("oktagon_odoo_golang_amqp/protoModel/productTemplate.proto", fileDescriptor_ad1a6a864f447bb7)
}

var fileDescriptor_ad1a6a864f447bb7 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xe5, 0x24, 0xcd, 0x9f, 0x49, 0x5b, 0xca, 0xa6, 0x42, 0x23, 0x84, 0xc0, 0x8a, 0x38,
	0xf8, 0x42, 0x90, 0xe0, 0x84, 0x38, 0x01, 0xbd, 0xe4, 0x80, 0x14, 0x0c, 0xf7, 0x68, 0xeb, 0x1d,
	0xb9, 0xab, 0xae, 0x3d, 0xc6, 0x5e, 0x83, 0xf8, 0x10, 0x7c, 0x4d, 0x3e, 0x07, 0xf2, 0x6c, 0x9c,
	0xa4, 0x22, 0x77, 0x6e, 0xef, 0xfd, 0xde, 0xec, 0xd3, 0x68, 0x35, 0xf0, 0x8e, 0xef, 0xbd, 0xce,
	0xb9, 0xdc, 0xb2, 0x61, 0xde, 0xe6, 0xec, 0x74, 0x99, 0x6f, 0x75, 0xf1, 0xbd, 0x7a, 0x5d, 0xd5,
	0xec, 0xf9, 0x33, 0x1b, 0x72, 0x9d, 0x34, 0x6d, 0xe6, 0xbf, 0x51, 0x51, 0x39, 0xed, 0x69, 0x25,
	0x91, 0x82, 0xc3, 0xc4, 0xf2, 0x77, 0x04, 0x8b, 0x4d, 0x98, 0xfa, 0xd8, 0x96, 0xc6, 0xd1, 0x0d,
	0x79, 0x6d, 0x9d, 0xba, 0x84, 0x81, 0x35, 0x18, 0xc5, 0x51, 0x32, 0x4c, 0x07, 0xd6, 0x28, 0x05,
	0xa3, 0x52, 0x17, 0x84, 0x83, 0x38, 0x4a, 0x66, 0xa9, 0x68, 0x15, 0xc3, 0xdc, 0x50, 0x93, 0xd5,
	0xb6, 0xf2, 0x96, 0x4b, 0x1c, 0x4a, 0x74, 0x8c, 0xd4, 0x33, 0x98, 0x39, 0xdb, 0xf8, 0x4d, 0x6d,
	0x33, 0xc2, 0x51, 0x1c, 0x25, 0x51, 0x7a, 0x00, 0x5d, 0x67, 0xc6, 0x8d, 0xc7, 0x33, 0x09, 0x44,
	0x2f, 0xff, 0x8c, 0x60, 0xb2, 0xdb, 0xe7, 0x7f, 0xed, 0xa0, 0x9e, 0xc0, 0xf8, 0x07, 0xbb, 0xb6,
	0x20, 0x1c, 0x0b, 0xdd, 0xb9, 0x8e, 0xff, 0x24, 0x9b, 0xdf, 0x79, 0x9c, 0x04, 0x1e, 0x9c, 0x7a,
	0x0e, 0x90, 0x69, 0x4f, 0x39, 0xd7, 0xbf, 0xd6, 0x06, 0xa7, 0xb2, 0xef, 0x11, 0x51, 0x4f, 0x61,
	0xda, 0x3b, 0x9c, 0xc9, 0x82, 0x7b, 0xaf, 0x96, 0x70, 0xde, 0xeb, 0x4f, 0x6c, 0x08, 0x41, 0xf2,
	0x07, 0xac, 0xeb, 0x6f, 0xb9, 0xf8, 0xaa, 0x1d, 0x35, 0x6b, 0x83, 0xf3, 0xd0, 0x7f, 0x20, 0x5d,
	0x7f, 0xef, 0xf0, 0x3c, 0xf4, 0xf7, 0x5e, 0xbd, 0x84, 0x8b, 0x96, 0x8b, 0x4d, 0x5b, 0x67, 0x77,
	0xba, 0xa1, 0xb5, 0xc1, 0x0b, 0x79, 0xfe, 0x10, 0x76, 0xbf, 0x78, 0x04, 0xf0, 0x32, 0xfc, 0xe2,
	0x11, 0x52, 0x57, 0x30, 0x6c, 0xee, 0x5b, 0x7c, 0x24, 0x49, 0x27, 0x15, 0xc2, 0xe4, 0xb6, 0xd6,
	0xa5, 0x59, 0x1b, 0xbc, 0x92, 0xce, 0xde, 0xaa, 0x6b, 0x38, 0x13, 0x89, 0x8f, 0x65, 0x3a, 0x98,
	0x6e, 0x4b, 0xdb, 0x84, 0x1b, 0x43, 0x15, 0x47, 0xc9, 0x34, 0xdd, 0x7b, 0xf9, 0xc1, 0x9a, 0xb4,
	0xa7, 0x1b, 0xed, 0x09, 0x17, 0xbb, 0x1f, 0xdc, 0x13, 0xf5, 0x05, 0x16, 0xd5, 0xbf, 0x47, 0x8a,
	0xd7, 0xf1, 0x30, 0x99, 0xbf, 0x79, 0xb1, 0x3a, 0xdc, 0xf3, 0xea, 0xc4, 0x2d, 0xa7, 0xa7, 0xde,
	0x2e, 0xdf, 0x03, 0x7c, 0x70, 0xae, 0x3f, 0xb5, 0x57, 0x30, 0xd9, 0x0d, 0x61, 0x24, 0xa5, 0x8b,
	0x13, 0xa5, 0x69, 0x3f, 0x73, 0x3b, 0x96, 0xf0, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e,
	0xd9, 0x8d, 0xc3, 0x85, 0x03, 0x00, 0x00,
}
